# Generated by Django 5.2.14 on 2026-05-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
                ('login_username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
            ],
            options={
                'db_table': 'citizen',
            },
        ),
        migrations.CreateModel(
            name='UrbanPlanner',
            fields=[
                ('planner_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('planner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('access_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'urban_planner',
            },
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('report_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('report_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('authority', models.ForeignKey(db_column='authority_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to='municipal_app.admin')),
                ('citizen', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='municipal_app.citizen')),
            ],
            options={
                'db_table': 'waste_report',
            },
        ),
    ]
